### PR TITLE
Listeners and Hooks

### PR DESCRIPTION
**Pull request by dandc87**
This implements a `setOnPageChangeListener()` for issue #10  and adds in a `getViewPager()` as forgotten about in issue #5.

Propose: increment to version 2.1.0 after this PR.

Please Review:
* @mluedke2

### CODE REVIEW

**Comment by mluedke2** [comment]
This is awesome!

I made a comment in code and updated the README.

Also, one question:

Can we now safely remove `attachOnPageChangeListener` from `ParallaxContainer`?  It doesn't seem necessary now, and the need to subclass is now gone with the new public methods.

**Comment by ppatriotis** [comment]
Would getting rid of `attachOnPageChangeListener` create backwards compatibility issues for people who implemented it that way already?

**Comment by vinc3m1** [comment]
Yeah I'd be careful removing API without deprecation or a major version bump

**Comment by mluedke2** [comment]
Yeah that's true, some people may have used it that way. How about keeping `attachOnPageChangeListener` in, but just annotating as `@Deprecated`?

**Comment by dandc87** [comment]
Added Deprectated to `attachOnPageChangeListener`

**Pull request merged**
